<?php
/**
 * Created by zouminqiang
 * Date: 2020/4/11 10:11
 */
namespace  app\api\controller;

use app\common\controller\Api;

class  Pay extends Api{

    protected $noNeedLogin = [];
    protected $noNeedRight = ['*'];

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }



}